# Generated by Django 3.2.2 on 2024-04-04 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_alter_box_hours_close'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='date_joined',
        ),
        migrations.AlterField(
            model_name='box',
            name='hours_close',
            field=models.TimeField(default=datetime.time(16, 50, 15, 644273), verbose_name='Hora de Cierre'),
        ),
    ]
