# Generated by Django 3.2.2 on 2024-04-04 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_auto_20240404_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='box',
            name='hours_close',
            field=models.TimeField(default=datetime.time(16, 50, 29, 847092), verbose_name='Hora de Cierre'),
        ),
    ]
