# Generated by Django 3.2.2 on 2024-04-04 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_auto_20240404_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='initial',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='box',
            name='hours_close',
            field=models.TimeField(default=datetime.time(16, 53, 6, 120759), verbose_name='Hora de Cierre'),
        ),
    ]
