# Generated by Django 3.2.2 on 2024-05-07 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_auto_20240404_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='hours_close',
            field=models.TimeField(default=datetime.time(21, 18, 56, 941864), verbose_name='Hora de Cierre'),
        ),
    ]
